### ISSUE TITLE
Updating README.md for more installation hints

### ISSUE THREAD

**Issue by rgiessmann** [snopt/snopt-python#4]
Dear all,

similar to issue https://github.com/snopt/snopt-python/issues/1, I experienced problems when installing snopt-python with precompiled snopt7, too. 

Having exported SNOPT7=$HOME/snopt7, but still experiencing errors, I fixed the build step (by investigating the setup.py files) by copying libsnopt7.so to $HOME/snopt7/lib (which is unfortunately not referenced in the readme files so far).

When executing the example files, however, I experienced the error: 

```
Traceback (most recent call last):
  File "snopt_solver.py", line 16, in <module>
    import snopt7_python        as     snopt
ImportError: No module named snopt7_python
```

My solution was to copy libsnopt7.so into /usr/lib/. It seemed that exporting the environment variable SNOPT7 was getting unnecessary then, too, and everything from building to running works fine now.

I would like to request the README files to be updated, if this behavior can be reproduced on other machines.

Thanks for your effort! Best,
   Robert

**Comment by gnowzil** [comment]
That took a long time... 

I've updated the README to explain the library location.  The interface looks in $SNOPT7/lib because I was assuming users had licensed source-code versions of SNOPT and this is the default library location.  It is possible to change this in snopt-python/snopt7/setup.py (note the explicit '/lib' on line 12).
